# Generated by Django 4.0.1 on 2022-01-10 12:56

from django.db import migrations, models
import openapi.models


class Migration(migrations.Migration):

    dependencies = [
        ("openapi", "0002_taskrecord_remove_testtask_task_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskrecord",
            name="package_state",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (10, "Created"),
                    (100, "Collected"),
                    (110, "Shipping"),
                    (120, "Arrived"),
                    (190, "OnHold"),
                    (200, "Success"),
                    (300, "Failed"),
                ],
                default=openapi.models.PackageState["Unknown"],
                max_length=16,
                verbose_name="任务状态",
            ),
        ),
        migrations.AlterField(
            model_name="taskrecord",
            name="task_state",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (10, "Created"),
                    (20, "Running"),
                    (30, "Paused"),
                    (40, "Completed"),
                    (50, "Failed"),
                    (100, "Cancelled"),
                ],
                default=openapi.models.TaskState["Unknown"],
                max_length=16,
                verbose_name="包裹状态",
            ),
        ),
    ]
