# Generated by Django 4.0.1 on 2022-01-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openapi", "0004_alter_taskrecord_package_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testtask",
            name="request_params",
            field=models.JSONField(default=dict, verbose_name="任务参数"),
        ),
    ]
